### ISSUE TITLE
wrap for custom collections

### ISSUE THREAD

**Issue by threat70** [JohnSundell/Wrap#38]
Hi.
In readme says that I can implement `WrapCustomizable` for my own custom collection, but Wrapper have only wrap(object:) method, While inside the library also wrap(collection: ) and wrap(dictionary: ) is available. Maybe make this methods public for easy implement `WrapCustomizable` for own collections?
Or there is some other way to do this?

**Comment by JohnSundell** [comment]
@threat70 Could you give an example of the ideal API you'd like to see, and post some sample code so that the use case becomes clear?

**Comment by threat70** [comment]
this methods already done in library, but in private extension.
I simple make extension with this methods `public`

and use:

```
extension SortedSet: WrapCustomizable {
    public func wrap(context: Any?, dateFormatter: DateFormatter?) -> Any?  {
        return try? Wrapper(context: context, dateFormatter: dateFormatter).wrap(collection: self)
    }
}
```

I feel that I'm doing something wrong, or really no other way to do this?
Thanks for answer

**Comment by JohnSundell** [comment]
I don't think exposing the `wrap(collection:)` method is a good solution, since it makes a bit too many assumptions about how it's being used (since it's an implementation detail of Wrap).

I suggest implementing `wrap(context:dateFormatter:)` from `WrapCustomizable` in your custom collection and doing the wrapping manually if you have a very custom collection type. For example, let's say I have a custom collection that uses a dictionary as its storage. To add Wrap support for it, I could then do:

```swift
struct MyCustomCollection {
    private var dictionary: [String : MyModel]
}

extension MyCustomCollection: WrapCustomizable {
    func wrap(context: Any?, dateFormatter: DateFormatter?) -> Any? {
        return dictionary.wrap(context: context, dateFormatter: dateFormatter)
    }
}
```

Closing this for now, let me know I can help you with anything else (gonna try to respond a bit quicker next time 😅)
